'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property ARC122() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARC122", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCAlienAquakeyboard() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCAlienAquakeyboard", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCBBMessagerie() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCBBMessagerie", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCclipboard() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCclipboard", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCdownload() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCdownload", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCfilemanager() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCfilemanager", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCfileserver() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCfileserver", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCicon_EraseData() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCicon_EraseData", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCIexplorer7a() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCIexplorer7a", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCkcmkwm() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCkcmkwm", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCkded() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCkded", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCkservices() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCkservices", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCksnapshot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCksnapshot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARClogoff() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARClogoff", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCnet() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCnet", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCPNG() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCPNG", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCrestart() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCrestart", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCsmile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCsmile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCTerminal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCTerminal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ARCTerminal1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ARCTerminal1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property crit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("crit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property info() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property infor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("infor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property kded() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("kded", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mat() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mat", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ques() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ques", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property WindowsTurn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("WindowsTurn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
